import jslint from '@eslint/js';
import vitest from '@vitest/eslint-plugin';
import prettier from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import tabroom from './config/eslint-tabroom.js';

import globals from 'globals';

import tabRequireAccess from './eslint-rules/tab-require-access.js';

export default [
	jslint.configs.recommended,
	importPlugin.flatConfigs.recommended,
	prettier,
	tabroom,
	{
		ignores  : [
			'*/data/models/**', //autogenerated by sequelize-auto
			'config/*',
			'*.config.js',
			'.gitignore'
		],
	},
	{

		files : ['**/*.js', '*.js'],
		rules : {
			'tab-require-access/tab-require-access': 'error',
			semi : 'error',
			'no-unused-vars' : [
				'error',
				{
					args : 'all',
					argsIgnorePattern : '^(err|req|res|next|opts)$',
				},
			],
		},
		plugins: {
			'tab-require-access': { rules: { 'tab-require-access': tabRequireAccess } },
		},
		languageOptions : {
			ecmaVersion : 2023,
			sourceType  : 'module',
			globals     : { ...globals.node },
		},
	},
	{
		files: ['**/*.test.js'],
		plugins: {
			vitest,
		},
		languageOptions: {
			globals: {
			  ...vitest.environments.env.globals,
			},
		},
		rules: {
			...vitest.configs.recommended.rules,
			'@typescript-eslint/unbound-method': 'off',
			// we use globals, so don't import things that are already global
			'vitest/no-importing-vitest-globals': 'error',
			// ensure that every test has at least one assertion to prevent false positives
			'vitest/expect-expect': [
			  'error',
			  {
				assertFunctionNames: [
				  'expect',
				  'assert',
				],
			  },
			],
		  },
	},
];
